# Generated by Django 2.2.2 on 2019-06-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkchanger', '0002_filenamemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileNameModel',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
